### PR TITLE
Mergeable capabilities

### PR DESCRIPTION
**Pull request by smortex**
When switching from home-cooked deployment of MCollective to Choria, my custom facts caching was replaced by [the one of the puppet-mcollective module, which is handled by cron](https://github.com/choria-io/puppet-mcollective/blob/110ae245ee5dbdcc77d4ddbae9e609cb7a746f3e/manifests/facts.pp#L54-L58).

Because Facter currently segfaults with a non-UTF-8 environment on FreeBSD, I decided to set UTF-8 locales by default on my nodes through `login.conf`, which is supported by your module :sunglasses: .

I propose here some enhancements that — thanks to Hiera 5 — allow:

* Ability to configure any class (instead of the default one);
* Ability to specify only the desired changes to the default values (through Hiera deep merging);
* Ability to specify different default values for different versions of FreeBSD (in case the default content change at some point in the future).

Unfortunately, it breaks compatibility with previous versions, but I could not find an efficient way of merging these new capabilities with the current API :worried: .

With these changes, I use the following configuration:

```puppet
include freebsd::login
```

```yaml
freebsd::login::classes:
  default:
    lang: C.UTF-8
    charset: UTF-8
```

Thank you for your feedback!

### CODE REVIEW

**Comment by xaque208** [comment]
Hi @smortex, thanks for the PR.  Now here is an old module.  This change looks great.  I was going to tell you that nobody uses this module and that all the features have been moved to xaque208/puppet-bsd, but then I see that the login features you are modifying here have not made it over there.

In any case, thanks for the contribution.  This should be much easier to add arbitrary login classes.

**Comment by smortex** [comment]
Wow, I completely missed `xaque208/puppet-bsd`… Do you think I should create a PR there to add this feature, maybe providing a generic `termcap` defined type used by a `login` class, in case at some point we want to add support for `/etc/termcap` (erf… looking into it seems a bad idea), `/etc/bootptab` and similar files?

**Comment by xaque208** [comment]
The puppet-bsd module has more of my attention for improvements, so that would be my personal preference, but as long as the code is useful to you I'm not really worried where it lives.

For the generic termcap type, I think "right" way to approach this is through augeas.  See https://github.com/hercules-team/augeas/pull/274

**Comment by smortex** [comment]
D'oh, didn't though about Augeas!  That's would to be a nice solution!

**Comment by xaque208** [comment]
@smortex Yeah, but you can see how long that PR has been open :\

**Comment by xaque208** [comment]
I think it just needs the tests to be improved.

**Comment by smortex** [comment]
I'll give a look.  For now, I am fixing the test suite on FreeBSD…  It currently fails, but I started to work on this in respect to the obvious portability issues: https://github.com/hercules-team/augeas/pull/499

There are 3 failures left:

* test-interpreter.sh
* test-api
* test-run

 The first one is related to parsing weird files with `\` … So I guess it will not help parsing termcap files which have loads of them :disappointed_relieved:

**Comment by bodgit** [comment]
Hello, as the person responsible for hercules-team/augeas#274 I do keep noticing the interest in it and personally I would still like that lens to work, the problem is every time I revisit the code I cannot seem to get Augeas to create a literal `\` character as part of a line-break separator. However I'm also too stubborn to just give up so the PR has festered.

I'm reticent to say it's a bug in Augeas but as the lens reads (simple) termcap-style files such as `/etc/login.conf` but can't seem to write a new record back out correctly makes me think it's a bug. I will try and raise another issue specifically for this behaviour to see if someone can pinpoint what's going on.

`/etc/termcap` is the ultimate test case for the lens as there's so much backslash-escaping and funky escape characters :wink:

**Pull request merged**
